#!/usr/bin/env bash
# with-packages curl niv gawk nix-wrapped nr
channel=${1:-nixos-unstable}
url=$(curl -LIs -o /dev/null -w '%{url_effective}' "https://nixos.org/channels/$channel")
version=$(echo "$url" | awk -F/ '{ print $NF }')
niv update $channel-channel -v $version

for pkg in qutebrowser alacritty signal-desktop firefox;do
  version=$(nix eval --raw ".#$pkg.version")
  niv update dmg-$pkg -v $version
done

node_version=$(nr -c node nodejs_latest --version)
url=https://nodejs.org/download/release/$node_version/node-$node_version-headers.tar.gz
sha256=$(nix-prefetch-url $url)
echo "builtins.fetchurl { url = \"$url\"; sha256 = \"$sha256\"; }" > pkgs/nle/node-headers.nix
