#!/usr/bin/env bash
set -eo pipefail

waterfox_version=$(curl https://cdn.waterfox.net/releases/linux64/installer/ |
  sed -En 's#.*href="waterfox-(G.*)\.en-US.*".*#\1#p' |
  sort -V |
  tail -n1
)
nr niv update waterfox -v "$waterfox_version"
nix run .#jitsi-meet.updateScript

# FIXME
# cd pkgs
# mv emborg{,~}
# mkdir emborg
# cd emborg
# nix run -f https://github.com/jpetrucciani/nix/archive/main.tar.gz pynix -- emborg
# mv pynixify/packages/* .
# rm -rf pynixify
# cd ..
# mv emborg~/default.nix emborg
# rm -rf emborg~
