name: build
on: { workflow_dispatch, push }
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        system: [x86_64-linux]
    runs-on: [nix, "${{ matrix.system }}"]
    steps:
      - uses: actions/checkout@v6.0.2
      # - run: nix-instantiate --eval -E 'with import ./. {}; clipscreen.src.gitRepoUrl'
      - run: nix run .#updates.clipscreen
