name: build
on: { workflow_dispatch, push }
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        system: [x86_64-linux, aarch64-darwin]
    runs-on: [nix, "${{ matrix.system }}"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: nix -L build --impure .#required-substitutes
      - run: nix -L build .#checks
      - run: ./result/bin/checks
      - run: ./result/bin/cached-refs-push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: cachix authtoken '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: cachix push kwbauson ./result
      - run: cachix pin kwbauson checks.'${{ matrix.system }}' ./result
        if: github.ref == 'refs/heads/main'
