name: publish-pins
on:
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    branches: [main]
    types: [completed]
jobs:
  publish:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - run: |
          nix run github:kwbauson/create-pin-refs -- kwbauson
          git config --global global user.name 'Keith Bauson'
          git config --global user.email 'kwbauson@gmail.com'
          git branch --delete --force pins
          git add --all
          git commit --message 'publish pins'
          git push --force
