name: publish-pins
on:
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    branches: [main]
    types: [completed]
jobs:
  publish:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - run: |
          nix run github:kwbauson/create-pin-refs -- kwbauson
          git config user.name 'Keith Bauson'
          git config user.email 'kwbauson@gmail.com'
          git branch --delete --force pins || true
          git switch --orphan pins
          mv pins pins-dir
          mv pins-dir/* .
          git add --all
          git commit --message 'publish pins'
          git push --force --set-upstream origin pins
