name: publish-pins
on:
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    branches: [main]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - run: |
          nix run github:kwbauson/create-pin-refs -- kwbauson
          git config user.name 'Keith Bauson'
          git config user.email 'kwbauson@gmail.com'
          git switch --orphan pins
          mv pins pins-dir
          mv pins-dir/* .
          git add --all
          git commit --message 'publish pins'
          git push --force --set-upstream origin pins
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
      - run: nix run github:kwbauson/create-pin-refs -- kwbauson
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './pins'
      - uses: actions/deploy-pages@v4
