name: sync-branches
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [flake.lock]
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh pr list --json autoMergeRequest,headRefName --jq '.[] | select(.autoMergeRequest != null) | .headRefName' |
             xargs -I% gh api --method POST '/repos/${{ github.repository }}/merges' -f head=main -f base=%
