name: updates
on:
  workflow_dispatch:
    inputs:
      source: { type: string }
  schedule: [cron: '0 7 * * *']
run-name: updates-${{ inputs.source || 'all' }}
env:
  source: ${{ inputs.source || 'all' }}
  title: '${{ env.source }}: update'
jobs:
  updates:
    name: updates-${{ inputs.source || 'all' }}
    runs-on: [nix, Linux, X64]
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v6.0.2
      - run: nix run .#updates.'${{ env.source }}'
      - uses: peter-evans/create-pull-request@v8.1.0
        id: cpr
        with:
          title: ${{ env.title }}
          commit-message: ${{ env.title }}
          branch: updates-${{ env.source }}
          delete-branch: true
      - if: ${{ steps.cpr.outputs.pull-request-number }}
        run: echo gh pr merge --auto --squash ${{ steps.cpr.outputs.pull-request-url }}
