name: updates
env:
  source: ${{ inputs.source || 'all' }}
  run-name: updates-${{ inputs.source || 'all' }}
  title: '${{ env.run-name }}: update'
run-name: ${{ env.run-name }}
on:
  workflow_dispatch:
    inputs:
      source: { type: string }
  schedule: [cron: '0 7 * * *']
jobs:
  updates:
    name: ${{ env.run-name }}
    runs-on: [nix, Linux, X64]
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v6.0.2
      - run: nix run .#updates.'${{ env.source }}'
      - run: git commit --author 'Keith Bauson <kwbauson@gmail.com>' -am '${{ env.title }}'
      - uses: peter-evans/create-pull-request@v8.1.0
        id: cpr
        with:
          title: ${{ env.title }}
          branch: ${{ env.run-name }}
          delete-branch: true
      # - if: ${{ steps.cpr.outputs.pull-request-number }}
      #   run: gh pr merge --auto --squash ${{ steps.cpr.outputs.pull-request-url }}
